# # Configuration de base
# listen=YES
# listen_ipv6=NO
# background=NO
# anonymous_enable=NO
# local_enable=YES
# write_enable=YES

# # Sécurité & Chroot
# chroot_local_user=NO
# allow_writeable_chroot=NO
# seccomp_sandbox=NO

# # Désactivation de PAM (cause fréquente de segfault)
# pam_service_name=NO
# check_shell=NO

# # Mode passif
# pasv_enable=YES
# pasv_min_port=21000
# pasv_max_port=21010
# pasv_address=127.0.0.1  # À adapter si vous êtes derrière un NAT/VM

# # Logs pour le débogage
# xferlog_enable=YES
# log_ftp_protocol=YES
# vsftpd_log_file=/var/log/vsftpd.log

# # Répertoire chroot vide (obligatoire pour Alpine)
# secure_chroot_dir=/var/run/vsftpd/empty


listen=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
chroot_local_user=NO
pam_service_name=NO
pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010
