# mode standalone
listen=YES
# pas d'accès anonyme
anonymous_enable=NO
# autoriser les utilisateurs locaux à se connecter
local_enable=YES
# permettre l'écriture
write_enable=YES
# confiner dans le répertoire home
chroot_local_user=YES
# nécesssaire pour écrire dans le chroot
allow_writeable_chroot=YES
# mode passif
pasv_enable=YES
# plage de ports pour le mode passif
pasv_min_port=21000
pasv_max_port=21010
# requis pour Alpine Linux
seccomp_sandbox=NO
